version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_DB: car_panel_development
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  pgdata:
